### ISSUE TITLE
builds software rather than package

### ISSUE THREAD

**Issue by drzraf** [tjend/make_deb_terraform#1]
I'd expect that package get builds from the source (eg: git repository or source tarball) rather than already compiled software.

**Comment by tjend** [comment]
I agree. However, as this currently works well enough for me, it is not one of my priorities.

**Comment by tjend** [comment]
Hashicorp has finally created their own apt repo, see https://www.hashicorp.com/blog/announcing-the-hashicorp-linux-repository.
